# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#  name = "Declaration"
#  url = "#hero"
#  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "My academia"
  url = "academicgallery/"
  weight = 50

[[main]]
  name = "Publications"
#  url = "#featured" # this is disabled by deependrad
  url = "publication/"
  weight = 40

[[main]]
  name = "Tips and tricks"
  url = "tipsntricks/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "https://github.com/DeependraD/tex-for-beauty/releases/download/v1.06/Deependra_CV.pdf"
  weight = 70
