---
title: 'The nature of code: Why is it'
author: Deependra Dhakal
date: '2020-09-23'
slug: the-nature-of-code-why-is-it
categories:
  - genetics
  - Plant Breeding
tags:
  - genetics
  - plant breeding
subtitle: ''
summary: ''
authors: []
lastmod: '2020-09-23T06:22:01+05:45'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Many find genetics, as a field of science on its own, charming. Many more are excited to learn about the science that fits seamlessly into complexity driven life of organisms, providing explanation for natural phenomena at both micro-evolutionary and macro-evolutionary scales. But only few find fascination with its deep running concepts, going down to more fundamental physical theories. This article tries to at least expose, if not laid satisfying argument, to some of fundamental questions in genetics concerning nature of code (mostly chemical behaviour). In particular, following are some of the questions I plan to touch upon (Credit goes to a student of mine who posed these questions one evening and left me pondering on details):

1. Why do progeny cell need to receive identical DNA strand from parents ?
2. Why do DNA have 5' to 3' orientation ?
3. What is the significance of "AT" rich origin of replication ?
4. Why is there higher GC content in the stem of hair pin loop ?
5. What happens if there is high GC contenet in DNA-RNA hybrid beyond hair pin ?

There are couple of interesting ideas alluded to by the questions above. For instance, the phenomena of progeny cells receiving identical copy of genetic material -- DNA from its parents is actually quite remarkable. Four years after double helix model of DNA structure proposed by Watson and Crick, two other scientists Meselson and Stahl provided the evidence that two strands of DNA separate and replicate in a very precise way so that no DNA breaks or alterations in newly formed as well as template strand are introduced [@holmes2008meselson]. 


--

@book{holmes2008meselson,
  title={Meselson, Stahl, and the replication of DNA: a history of" The most beautiful experiment in biology"},
  author={Holmes, Frederic Lawrence},
  year={2008},
  publisher={Yale University Press}
}

