---
title: Lentil should be the choice. Or should it?
author: Deependra Dhakal
date: '2019-02-26'
slug: lentil-should-be-the-choice-or-should-it
categories:
  - agriculture
  - Plant Breeding
  - productivity
tags:
  - agriculture
  - plant breeding
  - productivity
header:
  caption: ''
  image: ''
draft: true
---

# Background

World produced ??? lentil in 201???. 
Who are the top 10 producers during past 10 years ? 
What is the productivity ranking of Nepal globally ?
Present consumption trend in Nepal and globe.
Why lentil as a human diet is suitable. 

# Why lentil cultivation in Nepal is in retreat ?

## Do we have good varieties ?

## Do we have good husbandry-practice recommendations ?

## Are disease and pests really bouncing back ?

## Is consumption trend nurturing ?

## Is the market lopsided ? 

# What do we do now ?

## Breeding quick

## Quality assurance (of data and nutrition)

## Crop management recommendations

- Supplemental zinc fertilization just before the reproductive stage of crop is most responsive; It has demonstrated benefits on pollen and stigma morphology, pollen fertility and thus overall seed yield [@pandey2006zinc]. 

## Product diversification

## Fight with market. We should, but who ?
