---
title: Maize seed value chain
author: Deependra Dhakal
date: '2019-01-17'
slug: maize-seed-value-chain
categories:
  - agriculture
  - maize
tags:
  - agriculture
header:
  caption: ''
  image: ''
---

# Introduction

There are a great deal of influencers along the chain of generating finished seed material from a produce offered by farmers. As we discussed earlier in [this post](https://rookie.rbind.io/post/seed-business-process-management-guide/), the process takes on a fairly complex pathway while certification and processing requirements are being met. Carrying out the process requires resources, a large amount of them. This post tries to quantitatively explain a general expense scheme of a typical company in Maize seed business (Note, however, that the concepts generalize well to both Hybrid and OP seeds). So why approach to business management through the cost concept? I'll just bullet point some of the direct benefits of thinking quantitatively.

1. Cost value can be summarized in terms of monetary units.
2. Cost is traceable as each unit of inputs having bearing on cost can be studied individually
3. Cost can be compared. For example, cost of two input factor could be compared to get a reliable estimate of efficiency of operation.

Production employs scarce resources, every resource has cost associated with the consumable value it has.

