---
title: A socio economic perspective on role of farmer segment relationship for long
  term profitability of an agricultural enterprise
author: Deependra Dhakal
date: '2019-03-19'
slug: a-socio-economic-perspective-on-role-of-farmer-segment
categories:
  - Economics
  - agriculture
tags:
  - agriculture
authors: []
header:
  caption: ''
  image: ''
  preview: yes
draft: true
---

## Background

Business is a profit oriented endeavour. Higher the sales, more the profit; no doubt in that. But exactly what factors cause sales to rise, or how the end is met, is actually more involved. Then again, in an agro-enterprise (whose primary consumption is agricultural input) the process of meeting the end includes both a longer chain of actors as well as broad array of functional activites along the way of transforming input to produce.

Business thrives with relationship -- the environment that brings producer and their client together. 

Major agricultural products have niche based production and consumption too. For example, a seed enterprise can aim only as far to producing what is permitted by its locational suitablity. A business with processing plant located in terai region cannot, in general competatively, ??redress high quality vegetable seeds. Likewise, it is rational to specialize in particular variety/hybrid than others for extended-area grown crops such as rice and wheat because of higly localized demand of these crops. Tighter the association between producer and consumer the better, in terms of both location and goodwill relation. In this post, I will discuss more on the association of the latter form. Why this deserves special attention on the agri-enterprise part.

More is not always better

Better is always better



