---
title: 'Color charts: An introductory review on applications to qualitative crop phenotyping'
author: Deependra Dhakal
date: '2019-01-23'
slug: color-charts-an-introductory-review-on-applications-to-qualitative-crop-phenotyping
categories: []
tags: ['plant breeding', 'r', 'color charts', 'agriculture', 'phenotyping']
header:
  caption: ''
  image: ''
---

# Background

Colorimetry is a fascinating topic to discuss. In conjunction with the patterns of a natural world (See this awesome video about [fibonacci numbers and plants](https://www.youtube.com/watch?v=ahXIMUkSXX0)), colors could have mesmerizing feels. In this post and the follow-up article, we will discuss in details about colorimetric features of a universe made of plants, in particular, which are cultivated/adopted and have edible human values -- the agricultural crops. Then again, there are quite a large number of agricultural species to deal with. So, we will be making a touch down on some common crop species, i.e. Pea (*Pisum sativum*, wild counterpart of the famous [Lathyrus](https://en.wikipedia.org/wiki/Lathyrus) pea studied by Mendel) and Wheat (*Triticum aestivum*).

# Review:
- How relevent is color for characterizing objects?

    Colors are perceptible to almost everyone. The color perception of an object is a function of three main properties of light: absorption, relection and transmission. Light transmission is mainly concerned with the energy propagation through a medium and does not itself affect the medium or the object. Hence, the absorbance and reflectance pattern have major roles in imparting color to objects. The more an object absorbs light of certain wavelengths from visible spectrum the lesser it is perceptible to observer. On the other hand, certain wavelengths of light are more easily reflected and thus the observer percieves the spectrum due to the color sensation it gives to eyes. Some species of animal kingdom even have outlandish color perceptions; for example whales and dolphins are reported to have no sense of blue color perception, despite living in a primarily blue world ([New scientist magazine post](https://www.newscientist.com/article/dn664-colour-blind/)), and insects like butterfly are composed of richer composition of cone cells (cells responsible for photoreception, and thus to detect color) -- one study reported as much as 15 -- while humans only have three primary photoreceptor cells (red, green and blue). Some lucky people may be endowed with tetrachromatic vision, however, which allows for a much more distinct perception of color hues ([Cosmosmagazine post](https://cosmosmagazine.com/biology/incredible-bizarre-spectrum-animal-colour-vision)).
    
    Considering the enormity of plant kingdom, an immediate contrast that one can make about the organism is regarding the color variation. Other features might have to be more closely watched over to discern the differences. This is mostly because, morpho-, topological, textural and compositional features require comparative characterization while colorimetric features are more or less absolute in perception. It is rarely that mixes of colors, even if involved, can't be isolated and characterized properly. Furthermore, unlike morphometric features, colors indices can be quite easily tracked, usually for certain plane and for given resolution.
    
    Colors can now be quantified (easily more than ever). Advances in imaging technologies have enabled quantification of colors imparted by objects thereby adding a different dimension for comparative studies.

- What are the special roles assumed by color features in biology?
- How can colors be informative?
    - Is standardization of flower petal/leaf colors possible?
        - Crop phenology as supportive feature for color description.
          Crop phenology augments the color information. Why is this important for crop characterization? One of the reasons could be that trait expression in some crops is phenology dependent. Only during cetain stages of their life cycles, do some crops exhibit particular features. For example, the color intensity of flower petals have a gradient of color intensities along the margin and middle??? {Citation and elaboration needed}
        - Color variation along fine scale morpho-topological features.
- What insights do colors provide?
    - Genetic insights (about parental genetics of the respective trait).
          - See this link: [Genetic control of biosynthesis of anthocyans in sweet pea (Lathyrus odoratus l.) flowers](https://www.ncbi.nlm.nih.gov/pubmed/20536019)
    - Case study of [Sweet pea](https://en.wikipedia.org/wiki/Sweet_pea). Why not start with wiki article?
    - Case study of Wheat crop for leaf color characterization? What are the immediate benifits of characterizing foliage by color?
        - Fertilizer/nutrition status 
    - What evolutionary insights could be gleaned from color variation in crops. (Example case of entomophily)
    - Are there any color associated traits?

- Ways to express biological variation of petal/leaf color (not variegation)?
    - Color charts for discrete colorimetry
    - Computer vision techniques to quantitative colorimetry. (Just the summary about available options)
        - See this document: [An Instructional Guide for Leaf Color Analysis using Digital Imaging Software](https://www.fs.fed.us/ne/newtown_square/publications/technical_reports/pdfs/2005/ne_gtr327.pdf)
- How to deal with variegation?
- What are the downfalls of colorimetry based characterization?
- Color discretization: are there opportunities to extend existing system?
- Summary notes and conclusion
    - Use of color charts in biological research (Which is best? why?)
    - How to best summarize color associated trait information (Is phenological attribute enough to back the the trait information? What needs to be improved)?
